version: 2

# commands (one or more steps) reused in many jobs
commands:
  # all caches include a version in their name (e.g. foo-cache-v1), the version is an arbitrary number
  # that can be incremented to invalidate a cache in case of errors or other unforeseen circumstances
  save_plt_cache:
    steps:
      - run:
          name: Version files for caches
          command: elixir --version >> ELIXIR_VERSION
      - save_cache:
          name: Save PLT cache
          key: plt-cache-v1-{{ checksum "ELIXIR_VERSION" }}
          paths:
            - /home/circleci/repo/priv/plts
  restore_plt_cache:
    steps:
      - run:
          name: Version files for caches
          command: elixir --version >> ELIXIR_VERSION
      - restore_cache:
          name: Restore PLT cache
          key: plt-cache-v1-{{ checksum "ELIXIR_VERSION" }}

jobs:
  build:
    environment:
      PIPEDRIVE_COMPANY_SUBDOMAIN: company-subdomain
      PIPEDRIVE_API_TOKEN: invalid-token
    docker:
      - image: circleci/elixir:1.8.1

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --force --warnings-as-errors
      - run: mix credo
      - restore_plt_cache
      - run: mix dialyzer --halt-exit-status
      - save_plt_cache
      - run: mix coveralls
      - run: mix test
