version: 2
jobs:
  build:
    environment:
      PIPEDRIVE_COMPANY_SUBDOMAIN: company-subdomain
      PIPEDRIVE_API_TOKEN: invalid-token
    docker:
      - image: circleci/elixir:1.8.1

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.hex --force && mix local.rebar --force
      - run: mix deps.get
      - run: mix compile --force --warnings-as-errors
      - run: mix credo
      - run: mix dialyzer --halt-exit-status
      - run: mix coveralls
      - run: mix test
